### PR TITLE
Mok: fix compilation if neither VENDOR_DB_FILE nor VENDOR_CERT_FILE are used

### PR DESCRIPTION
**Pull request by diabonas**
Since commit 5b69b1bcaec6bb46983621f83daa68a1096b3f9b this scenario fails with the compilation error
```
.././src/mok.c:93:21: error: ‘vendor_authorized’ undeclared here (not in a function)
   93 |   .addend_source = &vendor_authorized,
      |                     ^~~~~~~~~~~~~~~~~
.././src/mok.c:94:19: error: ‘vendor_authorized_size’ undeclared here (not in a function); did you mean ‘vendor_authorized_category’?
   94 |   .addend_size = &vendor_authorized_size,
      |                   ^~~~~~~~~~~~~~~~~~~~~~
      |                   vendor_authorized_category
```

### CODE REVIEW

**Comment by diabonas** [comment]
The shim master branch has been force-pushed to remove he offending commit 5b69b1bcaec6bb46983621f83daa68a1096b3f9b, so this PR can be closed.
